server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: "/demo"
spring:
  main:
    banner-mode: off
  datasource:
    platform: h2
  jpa:
    generate-ddl: false
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
management:
  endpoint:
    shutdown:
      enabled: true
    reboot:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always

main:
  app:
    config-path: /etc/apps/dockerdemo
app:
  config-path: ${main.app.config-path}
