
INSERT INTO USER (ID, NAME)
    SELECT 1, 'Alpha' FROM DUAL UNION ALL
    SELECT 2, 'Beta' FROM DUAL UNION ALL
    SELECT 3, 'Gamma' FROM DUAL UNION ALL
    SELECT 4, 'Theta' FROM DUAL UNION ALL
    SELECT 5, 'Delta' FROM DUAL UNION ALL
    SELECT 6, 'Sigma' FROM DUAL UNION ALL
    SELECT 7, 'Epsilon' FROM DUAL UNION ALL
    SELECT 8, 'Zeta' FROM DUAL UNION ALL
    SELECT 9, 'Lemma' FROM DUAL UNION ALL
    SELECT 10, 'Omega' FROM DUAL;